### ISSUE TITLE
prints and error message nout outputted in Rhino terminal

### ISSUE THREAD

**Issue by DamienGilliard** [ibois-epfl/script-sync#40]
**Describe the bug**
Print statements and error message are not outputted in the Rhino terminal, making debugging difficult. This happens on Mac and Windows, since 8.10.

**To Reproduce**

1. Create a python file with the following content: 
```py
print("hello world")
```
Alternatively you can leave the parenthesis open to create an error: 
```py
print("hello world"
```

2. In Rhino, activate ScriptSync, and run the code by pressing F4

**Expected behavior**
The expected and current behavior are shown in the screenshots:

**Screenshots**
When working (expected): 
![image](https://github.com/user-attachments/assets/fd55ff25-1eba-42ce-81ef-9ffcc004cae8)

When not working (since 8.10): 
![image](https://github.com/user-attachments/assets/48cee717-4dd1-4a2e-82db-47b3f53d67b4)

The same applies to error message

**Desktop (please complete the following information):**
Tested on: 
- Windows:
 ❌ Rhino 8 SR11 2024-9-10 (Rhino 8, 8.11.24254.15001, Git hash:master @ d3c11108eae09fadc146928ba51b9b182a05303f)
License type: Educational Lab License, build 2024-09-10
 ❌ Rhino 8 SR10 2024-8-15 (Rhino 8, 8.10.24228.13001, Git hash:master @ f4c93f2b85de4dc69b50ed22f1b0d91445724d03)
License type: Educational Lab License, build 2024-08-15
✅ Rhino 8 SR5 2024-3-12 (Rhino 8, 8.5.24072.13001, Git hash:master @ e3530849b75f00b2b977766a567ae29b055837e9)
License type: Educational Lab License, build 2024-03-12

I have old Mac versions of Rhino , including 8.9, on my NAS, but I am in the train,
MacOS to come

 - VSCode 1.93.1

- ScriptSync 1.2.13

I will try to come up with a solution, but not in the next few days.

**Comment by 9and3** [comment]
Amazing bug report @DamienGilliard , thank you for it! I'll look into it asap.

**Comment by 9and3** [comment]
solved internally in Rhino 8.12 SRC https://discourse.mcneel.com/t/bug-report-scripteditor-run-is-not-printing-anymore/192075
